apiVersion: apps/v1
kind: Deployment
metadata:
  name: sunf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sunf
  template:
    metadata:
      labels:
        app: sunf
    spec:
      containers:
      - image: okteto.dev/sunf:latest
        name: sunf
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "731792e2-3a45-46f3-ac81-2726ab7d6cde"
        - name: Vless_Path
          value: "/dfhyt30RY"
        - name: Vmess_UUID
          value: "731792e2-3a45-46f3-ac81-2726ab7d6cde"
        - name: Vmess_Path
          value: "/xxbdf47FD"
        - name: Share_Path
          value: "/share233"
