apiVersion: apps/v1
kind: Deployment
metadata:
  name: gmoh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gmoh
  template:
    metadata:
      labels:
        app: gmoh
    spec:
      containers:
      - image: okteto.dev/gmoh:latest
        name: gmoh
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "20280653-ab9f-4c99-8fbd-79b207b70274"
        - name: Vless_Path
          value: "/sddgERY"
        - name: Vmess_UUID
          value: "20280653-ab9f-4c99-8fbd-79b207b70274"
        - name: Vmess_Path
          value: "/xcbdDGFD"
        - name: Share_Path
          value: "/share233"
