apiVersion: apps/v1
kind: Deployment
metadata:
  name: doou
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doou
  template:
    metadata:
      labels:
        app: doou
    spec:
      containers:
      - image: okteto.dev/doou:latest
        name: doou
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "233e5480-f348-42df-9b70-5f524db182ca"
        - name: Vless_Path
          value: "/dgfE70RY"
        - name: Vmess_UUID
          value: "233e5480-f348-42df-9b70-5f524db182ca"
        - name: Vmess_Path
          value: "/xbdDG5FD"
        - name: Share_Path
          value: "/share233"
