apiVersion: apps/v1
kind: Deployment
metadata:
  name: wegd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wegd
  template:
    metadata:
      labels:
        app: wegd
    spec:
      containers:
      - image: okteto.dev/wegd:latest
        name: wegd
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "6eced298-c227-48d5-98d8-970ea4b88d4b"
        - name: Vless_Path
          value: "/DFHFJ693"
        - name: Vmess_UUID
          value: "6eced298-c227-48d5-98d8-970ea4b88d4b"
        - name: Vmess_Path
          value: "/dhrDRYHT"
        - name: Share_Path
          value: "/share233"
