apiVersion: apps/v1
kind: Deployment
metadata:
  name: serb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serb
  template:
    metadata:
      labels:
        app: serb
    spec:
      containers:
      - image: okteto.dev/serb:latest
        name: serb
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "7a646dfd-4a7e-465e-8b17-0a0d1b6d9899"
        - name: Vless_Path
          value: "/dfhfgSFHFG"
        - name: Vmess_UUID
          value: "7a646dfd-4a7e-465e-8b17-0a0d1b6d9899"
        - name: Vmess_Path
          value: "/ndrerFNCHT"
        - name: Share_Path
          value: "/share233"
