apiVersion: apps/v1
kind: Deployment
metadata:
  name: wood
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wood
  template:
    metadata:
      labels:
        app: wood
    spec:
      containers:
      - image: okteto.dev/wood:latest
        name: wood
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "135608e1-ea6f-46fd-9613-dd8ebc0ff593"
        - name: Vless_Path
          value: "/DHRT457"
        - name: Vmess_UUID
          value: "135608e1-ea6f-46fd-9613-dd8ebc0ff593"
        - name: Vmess_Path
          value: "/CBDRHT067"
        - name: Share_Path
          value: "/share233"
