apiVersion: apps/v1
kind: Deployment
metadata:
  name: wsct
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wsct
  template:
    metadata:
      labels:
        app: wsct
    spec:
      containers:
      - image: okteto.dev/wsct:latest
        name: wsct
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "8e6e94a1-d29f-4ecf-bb91-55ec019a9216"
        - name: Vless_Path
          value: "/hsd70dfhr"
        - name: Vmess_UUID
          value: "8e6e94a1-d29f-4ecf-bb91-55ec019a9216"
        - name: Vmess_Path
          value: "/y1519xdre"
        - name: Share_Path
          value: "/share233"
