apiVersion: apps/v1
kind: Deployment
metadata:
  name: wtou
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wtou
  template:
    metadata:
      labels:
        app: wtou
    spec:
      containers:
      - image: okteto.dev/wtou:latest
        name: wtou
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "43ce78b1-5db0-48e8-acc0-5ed30d1f048d"
        - name: Vless_Path
          value: "/dhffgDHR"
        - name: Vmess_UUID
          value: "43ce78b1-5db0-48e8-acc0-5ed30d1f048d"
        - name: Vmess_Path
          value: "/gerrtyCBD9"
        - name: Share_Path
          value: "/share233"
