apiVersion: apps/v1
kind: Deployment
metadata:
  name: doyf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doyf
  template:
    metadata:
      labels:
        app: doyf
    spec:
      containers:
      - image: okteto.dev/doyf:latest
        name: doyf
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "9f644119-197c-4374-a56d-17c4bff93b05"
        - name: Vless_Path
          value: "/dfhyt30RY"
        - name: Vmess_UUID
          value: "9f644119-197c-4374-a56d-17c4bff93b05"
        - name: Vmess_Path
          value: "/xxbdf47FD"
        - name: Share_Path
          value: "/share233"
