apiVersion: apps/v1
kind: Deployment
metadata:
  name: hool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hool
  template:
    metadata:
      labels:
        app: hool
    spec:
      containers:
      - image: okteto.dev/hool:latest
        name: hool
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "82d954ac-b05a-4cf1-9ffb-ea90cc27a1f5"
        - name: Vless_Path
          value: "/edfhrt24"
        - name: Vmess_UUID
          value: "82d954ac-b05a-4cf1-9ffb-ea90cc27a1f5"
        - name: Vmess_Path
          value: "/dgdf5756"
        - name: Share_Path
          value: "/share233"
