apiVersion: apps/v1
kind: Deployment
metadata:
  name: werf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: werf
  template:
    metadata:
      labels:
        app: werf
    spec:
      containers:
      - image: okteto.dev/werf:latest
        name: werf
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "d044424e-0ef3-43df-9144-149dfbb461fd"
        - name: Vless_Path
          value: "/YR576dfj"
        - name: Vmess_UUID
          value: "d044424e-0ef3-43df-9144-149dfbb461fd"
        - name: Vmess_Path
          value: "/RE457nfg"
        - name: Share_Path
          value: "/share233"
