apiVersion: apps/v1
kind: Deployment
metadata:
  name: wood
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wood
  template:
    metadata:
      labels:
        app: wood
    spec:
      containers:
      - image: okteto.dev/wood:latest
        name: wood
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "cb4ca31e-fcf4-4202-bef4-b64319104785"
        - name: Vless_Path
          value: "/dfhf640"
        - name: Vmess_UUID
          value: "cb4ca31e-fcf4-4202-bef4-b64319104785"
        - name: Vmess_Path
          value: "/dhrtETR"
        - name: Share_Path
          value: "/share233"
