apiVersion: apps/v1
kind: Deployment
metadata:
  name: gert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gert
  template:
    metadata:
      labels:
        app: gert
    spec:
      containers:
      - image: okteto.dev/gert:latest
        name: gert
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "0323a72e-e245-4ac7-a162-4ee247234644"
        - name: Vless_Path
          value: "/DFHFdrrb"
        - name: Vmess_UUID
          value: "0323a72e-e245-4ac7-a162-4ee247234644"
        - name: Vmess_Path
          value: "/CBFTeryr"
        - name: Share_Path
          value: "/share233"
