apiVersion: apps/v1
kind: Deployment
metadata:
  name: wdou
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wdou
  template:
    metadata:
      labels:
        app: wdou
    spec:
      containers:
      - image: okteto.dev/wdou:latest
        name: wdou
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "32494042-8064-4a49-abe3-bbe62d7967fe"
        - name: Vless_Path
          value: "/dfgf54t"
        - name: Vmess_UUID
          value: "32494042-8064-4a49-abe3-bbe62d7967fe"
        - name: Vmess_Path
          value: "/dghgdf57m"
        - name: Share_Path
          value: "/share233"
