apiVersion: apps/v1
kind: Deployment
metadata:
  name: souy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: souy
  template:
    metadata:
      labels:
        app: souy
    spec:
      containers:
      - image: okteto.dev/souy:latest
        name: souy
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "5eb5e0f5-9d73-42f2-be84-7d9814478e8c"
        - name: Vless_Path
          value: "/weyer46DFHF"
        - name: Vmess_UUID
          value: "5eb5e0f5-9d73-42f2-be84-7d9814478e8c"
        - name: Vmess_Path
          value: "/hbdgdrCBFT"
        - name: Share_Path
          value: "/share233"
