apiVersion: apps/v1
kind: Deployment
metadata:
  name: sougd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sougd
  template:
    metadata:
      labels:
        app: sougd
    spec:
      containers:
      - image: okteto.dev/sougd:latest
        name: sougd
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "a84a6842-0380-4b50-9f81-78a0cbd04589"
        - name: Vless_Path
          value: "/dgfE70RY"
        - name: Vmess_UUID
          value: "a84a6842-0380-4b50-9f81-78a0cbd04589"
        - name: Vmess_Path
          value: "/xbdDG5FD"
        - name: Share_Path
          value: "/share233"
