apiVersion: apps/v1
kind: Deployment
metadata:
  name: doer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doer
  template:
    metadata:
      labels:
        app: doer
    spec:
      containers:
      - image: okteto.dev/doer:latest
        name: doer
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "c656a047-3a13-4940-9271-d45b73e35365"
        - name: Vless_Path
          value: "/dfhfgg37RY"
        - name: Vmess_UUID
          value: "c656a047-3a13-4940-9271-d45b73e35365"
        - name: Vmess_Path
          value: "/ndrerh96FD"
        - name: Share_Path
          value: "/share233"
