apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdou
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdou
  template:
    metadata:
      labels:
        app: sdou
    spec:
      containers:
      - image: okteto.dev/sdou:latest
        name: sdou
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "20280653-ab9f-4c99-8fbd-79b207b70274"
        - name: Vless_Path
          value: "/4679ERY"
        - name: Vmess_UUID
          value: "20280653-ab9f-4c99-8fbd-79b207b70274"
        - name: Vmess_Path
          value: "/06845dDGFD"
        - name: Share_Path
          value: "/share233"
