apiVersion: apps/v1
kind: Deployment
metadata:
  name: four
spec:
  replicas: 1
  selector:
    matchLabels:
      app: four
  template:
    metadata:
      labels:
        app: four
    spec:
      containers:
      - image: okteto.dev/four:latest
        name: four
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "969b45d6-90f3-4f37-a566-b5021fc57360"
        - name: Vless_Path
          value: "/dfhrhsd35"
        - name: Vmess_UUID
          value: "969b45d6-90f3-4f37-a566-b5021fc57360"
        - name: Vmess_Path
          value: "/xdrey1609"
        - name: Share_Path
          value: "/share233"
