apiVersion: v1
kind: Service
metadata:
  name: hool
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "hool"
    port: 8080
  selector:
    app: hool
